INSERT INTO PUBLIC.CUSTOMER VALUES(1, 'KIT TOTO');
INSERT INTO PUBLIC.CUSTOMER VALUES(2, 'SALIM GIBSON');
INSERT INTO PUBLIC.CUSTOMER VALUES(3, 'MARTIN DONA');
INSERT INTO PUBLIC.CUSTOMER VALUES(4, 'SIMO HAMZA');
